### PR TITLE
Add react-tooltip

### PR DESCRIPTION
**Pull request by kevinch**
screen shot 2018-04-20 at 09 50 17

### CODE REVIEW

**Comment by lbebber** [comment]
Underline breaks on linebreak, and breaks line incorrectly—both because of `display: inline-block`.
kapture 2018-04-20 at 14 04 03

**Comment by kevinch** [comment]
@lbebber isso não é tão importante pois é só para a demo.

**Comment by kevinch** [comment]
Style of the trigger should be free and not set. It could be a piece of text, icon etc.

**Comment by lbebber** [comment]
@kevinch Makes sense. I still think it'd be worth it creating components like I said using this one, but that can be done later.

**Comment by kevinch** [comment]
### react-tooltip
- use of `data` attributes
- complex, trigger and tip are two separate elements
- trigger must be `block` or `inline-block` to center the tip

### react-tippy 
- external css to be imported
- `div` as child (possibly `<p>`)

### rc-tooltip
- external css to be imported

**Pull request closed without merging**
