### PR TITLE
Added title to checkbox

### PR DESCRIPTION
**Pull request by saviomuniz**
#### What is the purpose of this pull request?

To add title attribute to checkbox outer div and get it as prop

#### What problem is this solving?

This provides an accessibility feature to the filter navigator in stores, but generically it provides a tooltip to the whole Checkbox component

#### How should this be manually tested?

https://savio--storecomponents.myvtex.com/apparel---accessories/hats/
https://savio--worldwidegolf.myvtex.com/shoes/Womens?map=c,specificationFilter_258

#### Screenshots or example usage

image

#### Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by cmdalbem** [comment]
AFAIK the `title` attribute is heavily discouraged by accessibility experts. A commonly shared article about the issue is this one, from the renowned accessibility consultants from Paciello Group. Have you had a chance to take a look? https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/

**Comment by emersonlaurentino** [comment]
> AFAIK, o `title`atributo é fortemente desencorajado por especialistas em acessibilidade. Um artigo comumente compartilhado sobre o assunto é este, dos renomados consultores de acessibilidade do Paciello Group. Você já teve a chance de dar uma olhada? https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/

@cmdalbem  good practice a11y is to use label together with the input of type checkbox, however in this specific case a toltip would solve.

**Comment by emersonlaurentino** [comment]
@ohmyguigs I made a list of components that need to receive a11y #850, however I'm writing a better document to explain what to do.

**Comment by cmdalbem** [comment]
> > AFAIK, o `title`atributo é fortemente desencorajado por especialistas em acessibilidade. Um artigo comumente compartilhado sobre o assunto é este, dos renomados consultores de acessibilidade do Paciello Group. Você já teve a chance de dar uma olhada? https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/
> 
> @cmdalbem good practice a11y is to use label together with the input of type checkbox, however in this specific case a tooltip would solve.

agreed, an actual tooltip would do the trick here in this case, not a `title` attribute.

**Comment by TasGuerciMaia** [comment]
@saviofelixmuniz Is this still needed? Will you merge it?

**Pull request closed without merging**
